language: ruby
rvm:
- 2.5.3
before_install:
  - gem update --system
  - gem install bundler
   - gem install rake
gemfile: Gemfile
deploy:
  provider: heroku
  api_key:
    secure: uMDhBP9bKUNg/sr2fKRicNvOPw6So8a+kS+6tST1Qdbc8Zs3RCd+rD8Baut1hSqJ/d3Szag4Ey+3qzNmkuWLIEG4nqtl+8flpHk8iGhTB7Pdf6fkpMwfdFr2JtgpiATmHDvSpWggF5oUKD/ADrIgSfrFRkyf19jCokyv/hdFCgSP0zZUJAqiMjgvwT4jykJwfzD2mf9RLYTdIaNQ5jJMZwoz5Z9fQCLGl1K9tVuMr7FVnbL2jv5ALV6yP2m9uUMki/hXAcvL1tOglA8Ad4qz7J5PF6gIt8Nb7mLk3yQfmAaAVXzt6SDYFvHDXFFN1jQ/djQNPJg1kkjaEVVYfWulUcAsUdcP4TrbmuDGTA7/58drLmnlvuZR2muFNqO9H23glJtj018itekGNgFMyzxu7QvgV5qEN+bO8dhEgPqZidDp8oZkwz/VGJ4fO/VTPvbfUMCBfpU25D69EJP8nRlcWS7qCk4a1nZxHIsfPXIBXrpcO56if0q68+i4X8dgq/JdQIkpsLf3UTT2o5Xh7C3x22cI7YI4n1hJ6onsM091/X0JtI+LjkJBz5M7lhzWtoxB7gSBC0ual6wTSlgtXrLOL4giqAOdjbskOU3M2QxblBusoult70ifp300QO0SIKccX18wglQaAMBVx3Pown9PbAA+FuPRqnSvwsgPJUEZ/fY=
